# Generated by Django 3.0.9 on 2020-08-05 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5242880)),
                ('lang', models.CharField(max_length=10)),
                ('sample_output', models.CharField(max_length=5242880, null=True)),
                ('ques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='practice.Question')),
            ],
        ),
    ]
