# Generated by Django 3.0.9 on 2020-08-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_output_testcase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='sample_answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sample_testcase',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='done',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='sample_output',
        ),
    ]
